[package]
name = "authentik-core"
version = "2024.8.3"
edition = "2021"
rust-version.workspace = true

[dependencies]
authentik-common = { path = "../common" }

sea-orm = { workspace = true }
serde = { workspace = true }
